### ISSUE TITLE
Should this be in an open repository?

### ISSUE THREAD

**Issue by bucktaylor** [npinnovations/cordova-plugin-nblue-serial#1]
@nealtovsen - I've got this in an open repository in my repository so Cordova can pull it in during a build. Not sure if you can do that when it is in a private repository. Nothing critical - your thoughts?

**Comment by nealtovsen** [comment]
I thought you were pointing the build tools at the local clone...?

But if we want to open-source it, that's fine with me. Ideally, someday it might make sense to clean it up and submit a PR to the original fork.

**Comment by nealtovsen** [comment]
Set repo to public.
